# Generated by Django 4.2.23 on 2025-06-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='childseat',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='childseat',
            name='type',
            field=models.CharField(choices=[('rear_facing', 'Rear Facing Seat'), ('forward_facing', 'Forward Facing Seat'), ('booster', 'Booster Seat')], max_length=50),
        ),
    ]
