# Generated by Django 4.2.23 on 2025-06-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_typeofride_alter_booking_type_of_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightinformation',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_info', to='api.booking'),
        ),
        migrations.AlterField(
            model_name='flightinformation',
            name='flight_number',
            field=models.CharField(max_length=50),
        ),
    ]
