# Generated by Django 5.2.3 on 2025-06-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emailverification'),
        ('api', '0005_alter_flightinformation_booking_and_more'),
    ]

    operations = [
    ]
