# Generated by Django 4.2.23 on 2025-07-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_servicearea_image2_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='type_of_ride',
            field=models.CharField(choices=[('from-airport', 'From Airport'), ('to-airport', 'To Airport'), ('point-to-point', 'Point to Point'), ('hourly-as-directed', 'Hourly as Directed'), ('wine-tour', 'Wine Tour'), ('tour', 'Tour'), ('prom', 'Prom'), ('weddings', 'Weddings')], max_length=50),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_obj', to='api.booking'),
        ),
        migrations.DeleteModel(
            name='TypeOfRide',
        ),
    ]
