# Generated by Django 4.2.23 on 2025-07-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
