# Generated by Django 4.2.23 on 2025-07-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_user_discount_used',
            field=models.BooleanField(default=False, help_text='True if the user has already used or forfeited the new user discount.'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('sedan', 'Sedan'), ('premium-suv', 'Premium SUV'), ('sprinter-van', 'Sprinter Van')], max_length=20),
        ),
    ]
