# Generated by Django 4.2.23 on 2025-07-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_new_user_discount_used_alter_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_discounted',
            field=models.BooleanField(default=False, help_text='Indicates whether any discount was applied to this booking.'),
        ),
    ]
