# Generated by Django 4.2.23 on 2025-07-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_booking_is_discounted'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='flat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional flat rate for the ride (overrides calculated price if used).', max_digits=10, null=True),
        ),
    ]
