# Generated by Django 4.2.23 on 2025-08-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_vehicle_flat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='service_areas/'),
        ),
    ]
