# Generated by Django 4.2.23 on 2025-08-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_service_image1_alter_servicearea_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
