# Generated by Django 4.2.23 on 2025-08-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_passenger_email_alter_passenger_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='reason',
        ),
    ]
