from .vehicle import *
from .booking import *
from .comment import *
from .stop import *
from .passenger import *
from .promo import *
from .childseat import *
from .service import *
from .service_area import *
from .payment import *
from .flight_info import *
from .contact import *
from .tax import *
from .type_of_ride import *
